# GRADLE OPTIONS
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

mod_version = 1.1.0-release.2
maven_group = com.mclegoman
mod_name = viewpoint

minecraft = 1.21.6-rc1
mappings = 1.21.6-rc1+build.1
fabric_loader = 0.16.14
fabric_api = 0.127.0+1.21.6
modmenu = 13.0.0-beta.1
sodium = mc1.21.5-0.6.13-fabric
quilt_config = 1.2.0
toml = 3.6.6